### ISSUE TITLE
Zarf configuration of HA or single-node deployment

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/uds-capability-rook-ceph#123]
**Describe the feature:**

Certain deployments require HA, while others cannot support HA deployments. This rook-ceph capability only supports a very specific HA configuration for the rook-ceph capability. Delivery engineers should be able to specify some deploy-time variables that will allow switching between HA, non-HA, and single-node deployment of the rook-ceph capability, and also some of the HA configurations, like Ceph monitor counts.

For example, some @defenseunicorns/leapfrogai deployments occur on edge or single-node devices with limited resources and no HA capability. Tweaking of these resources should be allowed during deploy time to adapt to the target deployment environment. 

At the moment, all deployments to a single-node cluster will fail due to the conflicts caused by the hard-coded HA deployment described in this capability.

**Acceptance criteria:**

- [ ] User Story 1
> Given... a delivery engineer is deploying this init package to a Kubernetes cluster
> When... the cluster is multi-node (master server, agents) and supports HA
> Then... the delivery engineer can specify deployment variables that affect HA configurations

- [ ] User Story 2
> Given... a delivery engineer is deploying this init package to a Kubernetes cluster
> When... the cluster is single-node (master server only) and DOES NOT support HA
> Then... the delivery engineer can specify deployment variables that turn off and reduce all HA-related configurations

**Extra Context:**

Maybe something like this in the `values.yaml` (just a quick mock, don't take seriously):

```yaml
# cephBlockPool configuration
cephBlockPool:
  enabled: true
  spec:
    failureDomain: host
    replicated:
      size: ###ZARF_VAR_CEPH_BLOCK_POOL_REPLICATED_SIZE###
  storageClass:
    isDefault: true
    reclaimPolicy: Retain
    allowVolumeExpansion: true
    volumeBindingMode: "Immediate"
    mountOptions: []
    parameters:
      imageFormat: "2"
      imageFeatures: layering
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
      csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/fstype: ext4

# cephFileSystem configuration
cephFileSystem:
  enabled: true
  spec:
    metadataPool:
      replicated:
        size: ###ZARF_VAR_CEPH_FILESYSTEM_METADATA_POOL_REPLICATED_SIZE###
    dataPools:
      - failureDomain: host
        replicated:
          size: ###ZARF_VAR_CEPH_FILESYSTEM_DATA_POOL_REPLICATED_SIZE###
        name: data0
    metadataServer:
      activeCount: ###ZARF_VAR_CEPH_FILESYSTEM_METADATA_SERVER_ACTIVE_COUNT### # Can be increased for HA
      activeStandby: true
      resources:
        limits:
          cpu: "2000m"
          memory: "4Gi"
        requests:
          cpu: "1000m"
          memory: "4Gi"
      priorityClassName: system-cluster-critical
  storageClass:
    isDefault: false
    pool: data0
    reclaimPolicy: Retain
    allowVolumeExpansion: true
    volumeBindingMode: "Immediate"
    mountOptions: []
    parameters:
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
      csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
      csi.storage.k8s.io/fstype: ext4

# cephObjectStore configuration
cephObjectStore:
  enabled: true
  spec:
    metadataPool:
      failureDomain: host
      replicated:
        size: ###ZARF_VAR_CEPH_OBJECT_STORE_METADATA_POOL_REPLICATED_SIZE###
    dataPool:
      failureDomain: host
      erasureCoded:
        dataChunks: 2
        codingChunks: 1
    preservePoolsOnDelete: true
    gateway:
      port: 80
      resources:
        limits:
          cpu: "2000m"
          memory: "2Gi"
        requests:
          cpu: "1000m"
          memory: "1Gi"
      instances: ###ZARF_VAR_CEPH_OBJECT_STORE_GATEWAY_INSTANCES### # Can be increased for HA
      priorityClassName: system-cluster-critical
  storageClass:
    reclaimPolicy: Retain
    volumeBindingMode: "Immediate"
    parameters:
      region: us-east-1

# HA configurations in `cluster-values.yaml` - similar to `dev-cluster-values.yaml`
mon:
  allowMultiplePerNode: ###ZARF_VAR_CEPH_MON_ALLOW_MULTIPLE_PER_NODE### # Set to true for single-node
  count: ###ZARF_VAR_CEPH_MON_COUNT###

osd:
  count: ###ZARF_VAR_CEPH_OSD_COUNT### # Can be set to 1 for single-node

[and so on...]
```
